### ISSUE TITLE
How do you set indent levels?

### ISSUE THREAD

**Issue by SykesJohn** [Kookweb-ir/razor-formatter#1]
This formatter pushes parts of my code off into column 246 and will indent 61 spaces in one shot rending the code unreadable. It would be great to limit it to 1 indent of N columns per level.

**Comment by lonix1** [comment]
+1
We need a setting to control indentation - number of spaces

**Comment by ghost** [comment]
i published new update and now you can set indent_size and indent_char.

see read me for more detail

**Comment by lonix1** [comment]
I appreciate the new feature. :+1: 

However isn't it better to have it as a config option: `File`-> `Preference` -> `Settings` ?

**Comment by bojbaj** [comment]
honestly, i choose easiest way for me. :)
i can't spent too much time to develop this extension and i will be thankful if anyone make this better.

**Comment by lonix1** [comment]
No problem :)

by the way, I updated, then restarted my vscode but it doesn't work with <kbd>ctrl-shift-I</kbd> - , am I doing it correctly?

**Comment by bojbaj** [comment]
yes, you did it correctly. that was my mistake. 
new update published and this bug should be fixed.
thank you for your alert :)
