### ISSUE TITLE
Formating razor files breaks build

### ISSUE THREAD

**Issue by LokiMidgard** [Kookweb-ir/razor-formatter#2]
I tried to format some of my razor files with this formatter. 

This breaks my build. I haven't inspected this further but I can provide you with the failing code.

This is the [change](https://github.com/nota-game/nota/commit/21c0724aaf4929957d46a115b034a88f899900af) that breaks the build. And this is the failing [AppVeyor build](https://ci.appveyor.com/project/LokiMidgard/nota/build/1.0.68)

**Comment by JesseChang** [comment]
Build fails due to this will put razor codes into one line (start with@) which dotnet sdk can't recognize.

**Comment by LokiMidgard** [comment]
So this tool is for the .net version of Razor. Thanks for the info.
